name: 'Run miri tests filtering unsupported'
description: 'Execute tests with miri and filter/format out those that failed because of unsupported functionality.'
inputs:
  cargoflags:
    description: 'Flags for cargo'
    required: false
    default: ''
  miriflags:
    description: 'Flags for miri'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: install jq
      run: |
        sudo apt update
        sudo apt-get install jq
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: execute miri
      id: miri-execution
      run: cargo miri test ${{ inputs.cargoflags }} --no-fail-fast -- -Z unstable-options --format json | jq -j --unbuffered 'include "formatting"; main' | ./exit_err_on_failed.sh
      shell: bash
      env:
        MIRIFLAGS: ${{ inputs.miriflags }} -Zmiri-panic-on-unsupported

